server:
  port: 8080
  tomcat:
    max-threads: 15


spring:
  cloud:
    function:
      definition: consumeOrder
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          produceOrder-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
            consumeOrder-in-0:
              consumer:
                configuration:
                  key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bindings:
        produceOrder-out-0:
          destination: ordertopicthoai
          producer:
            use-native-encoding: true
        consumeOrder-in-0:
          destination: ordertopicthoai
          group: consumeOrderGroup